name: alternate_icon_gen_core
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  path: '>=1.8.0 <2.0.0'
  dartx: '>=1.0.0 <2.0.0'
  collection: '>=1.15.0 <2.0.0'
  dart_style: '>=2.0.0 <3.0.0'
  mime: '>=1.0.0 <2.0.0'
  yaml: '>=3.0.0 <4.0.0'
  json_annotation: '>=4.4.0 <5.0.0'
  xml: '>=6.0.0 <6.2.0'

dev_dependencies:
  build_runner: '>=2.0.0 <3.0.0'
  json_serializable: '>=6.0.0 <7.0.0'
